### ISSUE TITLE
"You cannot onboard more than one PayPal seller!" error when creating any payment method after sylius.pay_pal

### ISSUE THREAD

**Issue by tifed** [Sylius/PayPalPlugin#171]
PayPalPaymentMethodListener always returns error if sylius.pay_pay already connected. 
[This](https://github.com/Sylius/PayPalPlugin/blob/master/src/Listener/PayPalPaymentMethodListener.php#L49) condition always returns true and no matter what factory you want to use

**Comment by Zales0123** [comment]
Hello @tifed! Yes, this is the simplification we decided to take due to some possible issues that having multiple PayPal payment methods in the application can lead to (see https://github.com/Sylius/PayPalPlugin/issues/115 and https://github.com/Sylius/PayPalPlugin/issues/147 for reference). 

For sure we would like to implement support for multiple PayPal payment methods (probably one per channel is a fair compromise), but we need to take care of the proper implementation, as it's definitely not trivial. In the meantime, you can try to override this service and provide your own logic. It would be definitely easier to handle it for the specific need than in a generic way how we must do it 🖖 🚀

**Comment by tifed** [comment]
@Zales0123 No no no... That error triggered even if you select ANY different payment method (offline - for example).

In other words it sounds like "You can`t add offline method coz you have paypal". 
[That](https://github.com/Sylius/PayPalPlugin/blob/master/src/Listener/PayPalPaymentMethodListener.php#L49) condition must look like 
```
if ($paymentMethod->getGatewayConfig()->getFactoryName() === 'sylius.pay_pal' 
    && $this->isTherePayPalPaymentMethod()) {
    ...
}
```

**Comment by Zales0123** [comment]
😱 ok, you're right 😄 it's weird we didn't notice it before 💃 

Would you like to open a PR with such a fix? It would be great 🎉 Thanks in advance!

**Comment by Zales0123** [comment]
Should be fixed with https://github.com/Sylius/PayPalPlugin/pull/172 🎉

**Comment by bellu** [comment]
I'm trying to add two different payPal gateway, on two different channels; but it seems that this is still not allowed.
